### ISSUE TITLE
Unable to find step 5 (App service container settings) in Azure Portal

### ISSUE THREAD

**Issue by eoumenwa** [microsoft/azuredevopslabs#687]
I could not find the step below when clicking on the App Service in Azure Portal

Navigate to the [Azure Portal](https://portal.azure.com/) and click on the App Service that was created at the beginning of this lab. Select the Container Settings option and provide the information as suggested and then click the Save button.

![image](https://github.com/microsoft/azuredevopslabs/assets/78841364/706e0b32-6821-459a-91df-3949277d8d2b)

**Comment by surajshenoy** [comment]
Hi @eoumenwa,

Yes, you will not find these options currently in the portal as Azure portal got enhanced a lot since we deployed this version of lab.

Thanks for letting us know, we will consider your feedback and update the lab content.

For now, please skip this part as it does not seem necessary.

Regards!!!

**Comment by eoumenwa** [comment]
Thank you
